"""
Reporter
Generates HTML and/or JSON test reports from results dict.
"""

import json
import os
from datetime import datetime


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>NetTest Report — {run_id}</title>
<style>
  :root {{
    --pass: #16a34a; --fail: #dc2626; --error: #d97706;
    --bg: #0f172a; --card: #1e293b; --border: #334155;
    --text: #e2e8f0; --muted: #94a3b8; --accent: #3b82f6;
  }}
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: 'Segoe UI', sans-serif; background: var(--bg); color: var(--text); padding: 2rem; }}
  h1 {{ font-size: 1.8rem; color: var(--accent); margin-bottom: 0.25rem; }}
  .meta {{ color: var(--muted); font-size: 0.85rem; margin-bottom: 2rem; }}
  .summary {{ display: flex; gap: 1rem; margin-bottom: 2rem; flex-wrap: wrap; }}
  .stat {{ background: var(--card); border: 1px solid var(--border); border-radius: 8px;
           padding: 1rem 1.5rem; min-width: 120px; text-align: center; }}
  .stat .num {{ font-size: 2rem; font-weight: 700; }}
  .stat .label {{ font-size: 0.8rem; color: var(--muted); margin-top: 4px; }}
  .pass-num {{ color: var(--pass); }} .fail-num {{ color: var(--fail); }}
  .suite {{ background: var(--card); border: 1px solid var(--border); border-radius: 8px;
            margin-bottom: 1.5rem; overflow: hidden; }}
  .suite-header {{ padding: 0.75rem 1.25rem; background: #253347; display: flex;
                   justify-content: space-between; align-items: center; }}
  .suite-name {{ font-weight: 700; font-size: 1rem; text-transform: uppercase;
                 letter-spacing: 0.05em; color: var(--accent); }}
  .suite-stats {{ font-size: 0.8rem; color: var(--muted); }}
  table {{ width: 100%; border-collapse: collapse; }}
  th {{ background: #1a2a3a; color: var(--muted); font-size: 0.75rem; font-weight: 600;
        text-transform: uppercase; letter-spacing: 0.05em; padding: 0.5rem 1rem; text-align: left; }}
  td {{ padding: 0.6rem 1rem; font-size: 0.85rem; border-top: 1px solid var(--border); }}
  tr:hover td {{ background: rgba(59,130,246,0.05); }}
  .badge {{ display: inline-block; padding: 2px 10px; border-radius: 999px;
            font-size: 0.72rem; font-weight: 700; letter-spacing: 0.05em; }}
  .PASS  {{ background: rgba(22,163,74,0.15);  color: var(--pass); }}
  .FAIL  {{ background: rgba(220,38,38,0.15);  color: var(--fail); }}
  .ERROR {{ background: rgba(217,119,6,0.15);  color: var(--error); }}
  .detail {{ color: var(--muted); max-width: 500px; word-break: break-word; }}
  footer {{ text-align: center; color: var(--muted); font-size: 0.75rem; margin-top: 2rem; }}
</style>
</head>
<body>
<h1>🔍 NetTest Report</h1>
<div class="meta">Run ID: {run_id} &nbsp;|&nbsp; {started_at} &nbsp;|&nbsp; {total} tests across {suite_count} suites</div>

<div class="summary">
  <div class="stat"><div class="num">{total}</div><div class="label">Total</div></div>
  <div class="stat"><div class="num pass-num">{passed}</div><div class="label">Passed</div></div>
  <div class="stat"><div class="num fail-num">{failed}</div><div class="label">Failed</div></div>
  <div class="stat"><div class="num" style="color:var(--accent)">{pass_rate}%</div><div class="label">Pass Rate</div></div>
</div>

{suites_html}

<footer>Generated by NetTest &nbsp;|&nbsp; {finished_at}</footer>
</body>
</html>"""


def render_suite(suite):
    rows = ""
    for t in suite["tests"]:
        rows += f"""
        <tr>
          <td>{t['name']}</td>
          <td><span class="badge {t['status']}">{t['status']}</span></td>
          <td class="detail">{t.get('detail', '')}</td>
        </tr>"""

    return f"""
<div class="suite">
  <div class="suite-header">
    <span class="suite-name">{suite['name']}</span>
    <span class="suite-stats">{suite['passed']} passed &nbsp;/&nbsp; {suite['failed']} failed &nbsp;|&nbsp; {suite['duration_s']}s</span>
  </div>
  <table>
    <thead><tr><th>Test</th><th>Status</th><th>Detail</th></tr></thead>
    <tbody>{rows}</tbody>
  </table>
</div>"""


def generate_report(results: dict, fmt: str = "both", output_dir: str = "reports"):
    os.makedirs(output_dir, exist_ok=True)
    run_id = results["meta"]["run_id"]
    meta   = results["meta"]

    pass_rate = round(meta["passed"] / meta["total"] * 100, 1) if meta["total"] else 0

    if fmt in ("json", "both"):
        json_path = os.path.join(output_dir, f"report_{run_id}.json")
        with open(json_path, "w") as f:
            json.dump(results, f, indent=2)
        print(f"\n📄 JSON report  → {json_path}")

    if fmt in ("html", "both"):
        suites_html = "".join(render_suite(s) for s in results["suites"])
        html = HTML_TEMPLATE.format(
            run_id      = run_id,
            started_at  = meta["started_at"],
            finished_at = meta.get("finished_at", ""),
            total       = meta["total"],
            passed      = meta["passed"],
            failed      = meta["failed"],
            pass_rate   = pass_rate,
            suite_count = len(results["suites"]),
            suites_html = suites_html,
        )
        html_path = os.path.join(output_dir, f"report_{run_id}.html")
        with open(html_path, "w", encoding="utf-8") as f:
            f.write(html)
        print(f"🌐 HTML report  → {html_path}")
